### ISSUE TITLE
Add Ben to team on openfree.energy website

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/openfreeenergy.github.io#29]
See https://github.com/OpenFreeEnergy/openfreeenergy.github.io/tree/main/_team for examples, e.g. https://raw.githubusercontent.com/OpenFreeEnergy/openfreeenergy.github.io/main/_team/ialibay.md

These are rendered at https://openfree.energy/team/

EDIT: Instructions added to README in #30.

**Comment by RiesBen** [comment]
this happend :)
