### ISSUE TITLE
Add Hannah to the website

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/openfreeenergy.github.io#61]
@hannahbaumann : As part of your onboarding, we also usually ask you to add yourself to the team page of the website!

There are instructions in the [README](https://github.com/OpenFreeEnergy/openfreeenergy.github.io/blob/main/README.md#adding-new-team-members) of this repo, you can see the recent PR where James added himself in #59, and you can see all of our individual pages [in the `_team/` directory](https://github.com/OpenFreeEnergy/openfreeenergy.github.io/tree/main/_team). The results, after merged, will show up at https://openfree.energy/team/

For a picture, you can either use an existing online image (several of us use our GitHub avatars), or you can upload a picture as part of your PR.

**Comment by hannahbaumann** [comment]
Added myself to the team page!

**Comment by mikemhenry** [comment]
Fixed with 263f86fbc24090b4cec58c90a5ddf1b7776db825
