### ISSUE TITLE
1.0 release post-publication

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfreeenergy.github.io#78]
Couple of things post-publication:

1. Is there a missing picture?
2. Bullet points are missing

i.e. "Relative Binding/Hydration Free Energy Calculations using the Hybrid Topology approach, including the capability of charge changing transformations Absolute Hydration Free Energy Calculations “Vanilla” Molecular Dynamics (MD) simulations Automated setup approaches for the calculations Automated analysis of results" should have bullet points.

Would you be able to update this accordingly @jameseastwood ?

**Comment by jameseastwood** [comment]
Sorry for pushing to main, but I fixed the bullet points. Not sure what's going on with the empty image frame -- it's not in the markdown.
